version: "3.2"
services:
  db:
    image: postgres:alpine
    environment:
      - POSTGRES_HOST_AUTH_METHOD=trust
  code:
    build: .
    volumes:
      - type: bind
        source: .
        target: /app
        consistency: delegated
    environment:
      - "DATABASE_HOST=db"
    depends_on:
      - db
